# workflow name
name: release

# on events
on:
  release:
    types: [created]

# jobs
jobs:
  # generate build cross-platform build files
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install all Go dependencies
        run: go get

      - name: Generate build files
        uses: thatisuday/go-build-action@v1
        with:
          platforms: "linux/amd64, darwin/amd64, windows/amd64"
          package: "demo"
          name: "math"
          compress: "true"
          dest: "dist"

      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*.tar.gz"