name: release

on:
  release:
    types:
      - created

jobs:

  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate build files
        uses: thatisuday/go-build-action@v1.0.2
        with:
          platforms: "windows/amd64, linux/amd64, darwin/amd64"
          package: ""
          name: "jim"
          compress: "true"
          dest: "dist"
          ldflags: "\"-X 'utils.Version=${{ github.ref_name }}'\""

      - name: Copy build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*.tar.gz"